### ISSUE TITLE
Severe memory leaks

### ISSUE THREAD

**Issue by xuzhongping** [rickytan/APNGImageSerialization#5]
Hi,using some class factory methods, such as `imageWithContentsOfFile`, will cause the resulting `UIImage `object to be unreleased because the `autorelease` rule is broken for `__attribute__((objc_method_family(new)))`.

**Comment by rickytan** [comment]
fixed by https://github.com/rickytan/APNGImageSerialization/commit/b4ce4d99a8e73a73bbe73428f750e4316b2a6635 , thanks for the feedback
